name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          cd client
          vercel --prod --confirm --token $VERCEL_TOKEN --name book-inventory-frontend

  backend-deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: frontend-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-book-inventory-backend" \
          -H "Authorization: Bearer $RENDER_API_KEY"
